spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
    username: postgres
    password: postgres
  jpa:
    database: postgresql
    generate-ddl: true
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true